[
{"name":"Andra Pradesh","id":"1"},
{"name":"Arunachal Pradesh","id":"2"},
{"name":"Assam","id":"3"},
{"name":"Bihar","id":"4"},
{"name":"Chhattisgarh","id":"5"},
{"name":"Goa","id":"6"},
{"name":"Gujarat","id":"7"},
{"name":"Haryana","id":"8"},
{"name":"Himachal Pradesh","id":"9"},
{"name":"Jammu and Kashmir","id":"10"},
{"name":"Jharkhand","id":"1"},
{"name":"Karnataka","id":"12"},
{"name":"Kerala","id":"13"},
{"name":"Madya Pradesh","id":"14"},
{"name":"Maharashtra","id":"15"},
{"name":"Manipur","id":"16"},
{"name":"Meghalaya","id":"17"},
{"name":"Mizoram","id":"18"},
{"name":"Nagaland","id":"19"},
{"name":"Orissa","id":"20"},
{"name":"Punjab","id":"21"},
{"name":"Rajasthan","id":"22"},
{"name":"Sikkim","id":"23"},
{"name":"Tamil Nadu","id":"24"},
{"name":"Telagana","id":"25"},
{"name":"Tripura","id":"26"},
{"name":"Uttaranchal","id":"27"},
{"name":"Uttar Pradesh","id":"28"},
{"name":"West Bengal","id":"29"},
{"name":"Andaman and Nicobar Islands","id":"30"},
{"name":"Chandigarh","id":"31"},
{"name":"Dadar and Nagar Haveli","id":"32"},
{"name":"Daman and Diu","id":"33"},
{"name":"Delhi","id":"34"},
{"name":"Lakshadeep","id":"35"},
{"name":"Pondicherry","id":"36"}
]
